apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-outbox
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.outbox.storageClass }}
  storageClassName: {{ .Values.outbox.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.outbox.size }}
